/**
 * localStorage helpers + seed initialization.
 * The canonical seed data comes from /seed-data.json (generated by scripts/generate-samples.mjs).
 * On first run the app fetches it. The "Reset Demo" button re-fetches and overwrites.
 */
import { INVOICE_CATALOG, seedStatus, FACILITIES, PAYMENT_POINTS_DATA } from './invoiceCatalog.js'

export const STORAGE_KEY      = 'jireh_claims'
export const SEED_VERSION_KEY = 'jireh_seed_version'
export const CURRENT_SEED_VERSION = '2.0.0'  // bump → forces re-seed on next load

// Re-export for use in components
export { FACILITIES as JUMUIA_FACILITIES }
export const PAYMENT_POINTS = PAYMENT_POINTS_DATA.map((p) => p.name)

// ── Build claims from the catalog (fallback if fetch fails) ─────────────────

function buildClaimsFromCatalog() {
  return INVOICE_CATALOG.map((inv, idx) => {
    const status = seedStatus(idx)
    return {
      id:             `claim-seed-${idx}`,
      invoiceNumber:  inv.invoiceNumber,
      amount:         inv.amount,
      items:          inv.items,
      facility:       inv.facility,
      paymentPoint:   inv.paymentPoint,
      date:           inv.date,
      submittedAt:    (status === 'disbursed' || status === 'processing') ? `${inv.date}T08:30:00` : null,
      status,
      claimId:        (status === 'disbursed' || status === 'processing') ? `CLM-${200000 + idx}` : null,
      rejectionReason: status === 'rejected' ? 'Amount mismatch — please review and resubmit.' : null,
    }
  })
}

// ── Initialization (synchronous fallback first, then async JSON fetch) ──────

export function initializeStorage() {
  const existing = localStorage.getItem(SEED_VERSION_KEY)
  if (existing === CURRENT_SEED_VERSION) return  // already up to date

  // Synchronous fallback — populate from catalog immediately
  const claims = buildClaimsFromCatalog()
  localStorage.setItem(STORAGE_KEY, JSON.stringify(claims))
  localStorage.setItem(SEED_VERSION_KEY, CURRENT_SEED_VERSION)
}

/**
 * Fetch /seed-data.json and overwrite localStorage.
 * Used by the "Reset Demo" button. Returns the fresh claims array.
 */
export async function resetToSeedFile() {
  const resp = await fetch('/seed-data.json')
  if (!resp.ok) throw new Error(`Failed to fetch seed-data.json: ${resp.status}`)
  const { claims } = await resp.json()
  localStorage.setItem(STORAGE_KEY, JSON.stringify(claims))
  localStorage.setItem(SEED_VERSION_KEY, CURRENT_SEED_VERSION)
  localStorage.removeItem('jireh_claimed_set')  // clear submitted invoices too
  return claims
}

// ── CRUD helpers ─────────────────────────────────────────────────────────────

export function getClaims() {
  try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]') }
  catch { return [] }
}

export function saveClaims(claims) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(claims))
}

export function addClaim(claim) {
  const claims = getClaims()
  claims.unshift(claim)
  saveClaims(claims)
}

export function addClaims(newClaims) {
  saveClaims([...newClaims, ...getClaims()])
}

export function updateClaim(id, updates) {
  const claims = getClaims()
  const idx = claims.findIndex((c) => c.id === id)
  if (idx !== -1) { claims[idx] = { ...claims[idx], ...updates }; saveClaims(claims) }
}
